### ISSUE TITLE
Can you provide the file of llff_3v?

### ISSUE THREAD

**Issue by whalien-902** [SJoJoK/VGOS#3]
![image](https://github.com/SJoJoK/VGOS/assets/102122699/c1cea0d7-3ad2-4e7d-bded-7d09aa942350)
 Can you provide configs files related to the three-view LLFF dataset in the paper?
![image](https://github.com/SJoJoK/VGOS/assets/102122699/7aca3839-0f50-4e15-899c-ea9d62d68fe0)

**Comment by SJoJoK** [comment]
You can run 
```
$ zsh train_script/llff/llff_3v.sh
```
to re-conduct the experiments on the LLFF dataset. 
Besides, I've just uploaded `room.py` to align with the README, sorry for the inconvenience.

**Comment by whalien-902** [comment]
thanks
