### ISSUE TITLE
Wrong Parameter Names in room.py

### ISSUE THREAD

**Issue by R-penguins** [SJoJoK/VGOS#5]
When I run the program as instructed, the following error is reported

> get_training_rays: start
get_training_rays: finish (eps time: 0.002771139144897461 sec)
Traceback (most recent call last):
  File "/home/user/dev/VGOS/run.py", line 1422, in <module>
    train(args, cfg, data_dict,writer)
  File "/home/user/dev/VGOS/run.py", line 1245, in train
    scene_rep_reconstruction(
  File "/home/user/dev/VGOS/run.py", line 754, in scene_rep_reconstruction
    if cfg_train.N_rand_sample:
  File "/home/user/dev/DirectVoxGO/venv/lib/python3.10/site-packages/mmcv/utils/config.py", line 37, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'N_rand_sample'

Then I found out that the naming of parameters is different in room.py and default.py:
![Screenshot 2024-11-15 235510](https://github.com/user-attachments/assets/5dc89b65-18bf-47ca-81b7-e3cd18d676dd)

I suppose the following should be equivalent? Because the names listed in room.py are not used elsewhere in the codebase.
| room.py | default.py |
| --- | ----------- |
| N_rand_rand | N_rand_sample |
| x_mid_perc | x_mid |
| grid_anneal | voxel_inc |
| x_init_perc | x_init_ratio |

and so on.

If I change the names in room.py to those equivalent names the program would run.

Although it's pretty slow, taking me 30 mins plus on RTX3060.

Could you kindly take a look at this and update the correct file for room.py? If it is just a naming change I can make a pull request as well but I'm not sure if the parameters are right...

**Comment by SJoJoK** [comment]
Hi,
Thank you for this detailed feedback, I'll check this when I'm available.
The changed name is because of a clear-up before we release the code, and there may be something wrong.
As for the speed, because we built VGOS on the top of DVGO, so we will have a similar speed with DVGO on the same device.

**Comment by SJoJoK** [comment]
Hi,
You are right, there are something wrong when I refactor the codes, I will update the correct config.
P.S. I've tested with my A6000 machine and it takes about 5 mins. Anyway, you can try again with the updated config
![image](https://github.com/user-attachments/assets/1d5bc779-f61f-4829-9bec-fe48be92a140)
Sorry for any confusion caused.

**Comment by R-penguins** [comment]
Thank you for your quick response and update! I've tested on the updated config and it works. 👍

**Comment by SJoJoK** [comment]
Glad to help:)
